### ISSUE TITLE
Application Throughput

### ISSUE THREAD

**Issue by martin146** [nyuwireless/ns3-mmwave#10]
Hello,

could you please help me with some issues? When I simulate scenario with 3GPP model without any application (TCP, UDP) transmission speed is slightly over 3 Gbps, which is ok. But If I try to setup TCP or UDP application transmission speed falls dramatically. Throughput is between 120Mbps. Also in file RxPacketTrac some frames missing (are dropped?).

Thank you in advance.

**Comment by MengleiZhang** [comment]
You might need to increase buffer size. Such as ns3::TcpSocket::SndBufSize and ns3::TcpSocket::RcvBufSize.
