### ISSUE TITLE
problem of mmwave-example.cc

### ISSUE THREAD

**Issue by li654321** [nyuwireless/ns3-mmwave#12]
Could you please explain the meaning of column in RxPacketTrace.txt ?

**Comment by MengleiZhang** [comment]
The meaning of each column is the following,

1. Downlin/Uplink	2. frame #	3. subframe #	4. starting symbol	5. total symbol #	6. cellId	7. rnti	8. transport block size	9.mcs	10. rv for HARQ	11. SINR(dB)	12. true if packet is corrupted	13.error probability of this transport block.

Menglei

**Comment by li654321** [comment]
Firstly，thank you for your quick reply!
Secondly, I have some other issues. If I want to get distance vs rate of Packet loss and distance vs delay of time graph,how to modify the mmwave-example.cc?
I am beginning to study it,please explain it in detail. Thank you very much!

**Comment by li654321** [comment]
For the statistics of the frame, why is start with 16 in the RxPacketTrace.txt?

**Comment by MengleiZhang** [comment]
If you use ConstantVelocityMobilityModel, you should be able to compute the distance from the time, which is distance = time*speed. For more information, pleas check the mobility module.

If you are talking about TCP or UDP packet loss rate, I am not familiar with it and  please check the Internet module.

For the delay, if you are talking about RTT, you may take a look the mmwave-tcp-multiflow.cc <http://mmwave-tcp-multiflow.cc/>, where the RTT are recorded in a txt file.

The reason the the first packet arrives at frame 16 is because of the initial access process takes some time, i.e., exchange control messages and establish data channel.

Menglei

**Comment by li654321** [comment]
hi
Would you have the explain of mmwave-tcp-multi-ue.cc?

**Comment by MengleiZhang** [comment]
This is for multiple UE and connecting to same base station, each UE received a long TCP flow from a different remote server.

**Comment by li654321** [comment]
In the mmwave-tcp-multi-ue.cc,I want to track the process of the packet from remote sever to UE, how  to do it?
In the function of "Traces()",I add to TraceSources of "Rx" and "Tx", why is that the size of packet is 0 in the txt file about "Rx"  and  the size of packet is 60000 in the txt file about "Tx"?
In the mmwave-tcp-multi-ue.cc, the second column of "RTT.txt" file refer to that period of time？

**Comment by li654321** [comment]
In the mmwave-tcp-multi-ue.cc , I add to "sourceApps.Get(i)->TraceConnectWithoutContext("Tx", MakeBoundCallback(&Tx,stream1))" that is similar to "sinkApps.Get(i)->TraceConnectWithoutContext("Rx",MakeBoundCallback (&Rx, stream));", why is that the size of packet is 512?

**Comment by MengleiZhang** [comment]
Hi,

We appreciate that you are using our mmWave module and we know it is hard to start with, but please understand we can only help you fix issues or bugs related to our mmWave module. We are not responsible of helping your research.

1. To track the packet, you should be able to use debugger to understand the flow and log out the information.
2. I could not understand your problem.
3. The format of RTT.txt file is: at time t(column 1), RTT is changed from (column 2) to (column 3).

For the question of the following email, you should read more about the Internet module and the attributes system.

**Comment by li654321** [comment]
Hi,
firstly, thank you for your reply very much!
secondly, I want to ask what is the function of 
“Ptr<Ipv4StaticRouting> remoteHostStaticRouting = ipv4RoutingHelper.GetStaticRouting (remoteHost->GetObject<Ipv4> ());
remoteHostStaticRouting->AddNetworkRouteTo (Ipv4Address ("7.0.0.0"), Ipv4Mask ("255.255.0.0"), 1)”
in the mmwave-tcp-multi-ue.cc?

**Comment by MengleiZhang** [comment]
It adds a rule to the routing table
<https://en.wikipedia.org/wiki/Routing_table>.

Menglei

**Comment by EliseuFelipe** [comment]
Do the "6. cellId" means the source node of this packet ?

**Comment by mychele** [comment]
Hi, it is the base station that sent/received the packet: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces

**Comment by EliseuFelipe** [comment]
Hi, I really appreciate your response, but could you tell me if the colunm ccId is about the sender or the receiver node ? im not sure about it.
