### ISSUE TITLE
D2D scenario

### ISSUE THREAD

**Issue by AleksandraLo** [nyuwireless/ns3-mmwave#18]
Hi,

is it possible to simulate device to device communication using your module?

**Comment by MengleiZhang** [comment]
Hi,

No, it is not implemented.

Menglei

**Comment by EliseuFelipe** [comment]
Hi, it is implemented now ? I would like to simulate 3 nodes where n0 makes a broadcast to n1 and n2. After that I would like to set n0 and n2 out of range of each other and makes n0 communicate with n2 through n1. It is possible using the current version ? Thank you.

**Comment by mychele** [comment]
Hi, we recommend checking this out: https://github.com/signetlabdei/millicar It is a new ns-3 module that implements the NR sidelink.
