### ISSUE TITLE
scheduling

### ISSUE THREAD

**Issue by biljkus** [nyuwireless/ns3-mmwave#26]
Hi,
just a quick question about scheduling.  I used 3gpp channel example, and I increased the UDP rate by 100 times (by reducing the UDP interval to 10). I noticed that there are great variations in TB size among consecutive subframes (they correspond to the assigned numbers of symbols). This behaviour is the same for both RR and PF flex TTI schedulers, and it continues like this till the end of simulation (1second).  However, I would like to understand why these variations happen.

frame	subF	1stSym	symbol#	cellId	rnti	tbSize	mcs	rv	SINR(dB)	corrupt	TBler
...
DL	513	3	1	1	2	1	1776	28	0	48.7193		0	0
DL	513	4	1	6	2	1	10685	28	0	48.7301		0	0
DL	513	5	1	1	2	1	1776	28	0	48.7405		0	0
DL	513	6	1	6	2	1	10685	28	0	48.7272		0	0
DL	513	7	1	1	2	1	1776	28	0	48.729		0	0
DL	513	8	1	6	2	1	10685	28	0	48.7263		0	0
DL	513	9	1	1	2	1	1776	28	0	48.7309		0	0
DL	514	0	1	6	2	1	10685	28	0	48.7248		0	0
DL	514	1	1	1	2	1	1776	28	0	48.7344		0	0
DL	514	2	1	6	2	1	10685	28	0	48.7213		0	0
DL	514	3	1	1	2	1	1776	28	0	48.7252		0	0
DL	514	4	1	6	2	1	10685	28	0	48.7307		0	0
DL	514	5	1	1	2	1	1776	28	0	48.7156		0	0
....

Thanks,
Biljana

**Comment by MengleiZhang** [comment]
Hi Biljana,

The MAC layer frame support dynamically allocate OFDM symbols to each UE according to the buffer size in the RLC layer. That is, if the UDP data rate is not high enough, the RLC buffer would not be able to occupy the entire bandwidth, then only several symbols of each subframe are allocated.

**Comment by biljkus** [comment]
Seems that LteRlcUmLowLat needed some parameters adjustment. I increased the buffer size and the bsr report frequency, and now it is fine.
