### ISSUE TITLE
Buildings direct interference

### ISSUE THREAD

**Issue by xzeman43** [nyuwireless/ns3-mmwave#27]
Hello, I am trying to simulate direct building interference as follows. For simplicity, there is only 1 enb and 1 ue. The enb (orange cross) is static for the whole scenario and ue(yellow line) is moving in a line alongside the ue a can be seen on the picture attached. [Drawing1.pdf](https://github.com/nyuwireless/ns3-mmwave/files/1201297/Drawing1.pdf). The light green lines are there just for orientation where it should probably start covering the line of sight (now little inaccurate as the ue position was shifter 5 more meters in the y axis). 

![image](https://user-images.githubusercontent.com/15198403/28982176-2176dde6-7955-11e7-98dc-5e0004ee05af.png)

My question lies in the produced SINR results which do not look good. In the place where building is directly between ue and enb the SINR rises. This does not make sense as in 72GHz range it should block the signal theoretically. Can you please point me towards what I am doing wrong?

I am attaching also my code:
[SimpleObstacleCode.txt](https://github.com/nyuwireless/ns3-mmwave/files/1201321/SimpleObstacleCode.txt)

and results:
![image](https://user-images.githubusercontent.com/15198403/28982087-c1ecf770-7954-11e7-9282-b76d83742739.png)

If you will need more information please let me know and I will try to provide them or explain my problem better :)

Thank you

**Comment by MengleiZhang** [comment]
Hi,

The results make sense to me. What is your doubt?

**Comment by Sourjya9015** [comment]
Hi,

Like Menglei commented, the results do make sense. Explanation below:

1. For LoS cases, @0 and beyond 90 the SINR is very high, i.e. above 15 dB.

2. For the NLoS case the SINR is generally low. I think the link improvement between 30 and 50 is tripping you off. The improvement in the link between 30 and 50, I think, is caused by receiving more reflected paths. Although, notice that the SINR is still below 10 dB, i.e. not comparable with the LoS case.

I hope I have interpreted the plot and figure correctly. In future please label the axes for clarity.

**Comment by xzeman43** [comment]
The LOS cases look quite OK to me. But the NLOS should not work at all from what I observed at real measurements (at this frequency it actually cannot go through the building and there is no other objects to reflect from).  So why there is the peak inbetween? My expectations were that there would be none as I mentioned in the parentheses... 

Btw I am sorry for the labels. On the picture bottom line is X and the vertical one is Y. On the graph horizontal is distance in meters and vertucal SINR...

**Comment by MengleiZhang** [comment]
For simulation, the propagation loss in NLOS is simply a function of distance tween UE and ENB. Therefore, as the UE moves closer to the ENB, The SINR is increased.

Menglei

**Comment by xzeman43** [comment]
Ok thank you very much for confirmation. So basically I can make larger the loss added by building or adequately adjust the formula.

**Comment by MengleiZhang** [comment]
Sure. You can find the where the propagation loss is computed, and change the formula accordingly.

Menglei

**Comment by mychele** [comment]
If you are using the 3GPP channel model, you may also want to read this
https://arxiv.org/abs/1702.04822
Michele

Il 04 ago 2017 11:00 PM, "Menglei" <notifications@github.com> ha scritto:

> Sure. You can find the where the propagation loss is computed, and change
> the formula accordingly.
>
> Menglei
>

**Comment by xzeman43** [comment]
Thank you for all valuable comments!
