### ISSUE TITLE
mmwave-amc-test.cc Question

### ISSUE THREAD

**Issue by DmitarC** [nyuwireless/ns3-mmwave#5]
Could you please explain these lines is mmwave-amc-test.cc script?
The names suggest that these are SNR values in dB, but the comments are indicating that these are, in fact, distances in meters?

_double snrIncDb = 0.1; // increment by 10 meters 
double snrMinDb = -7.0;  // eNB-UE distance in meters 
double snrMaxDb = 30;  // eNB-UE distance in meters_ 

also, later on, there is a line:

_uePositionAlloc->Add (Vector (snrMinDb, 0.0, 0.0));_

which also suggest that snrMinDb is the distance in meters actually?

But:
**snrInit** changes from **snrMinDb** to **snrMaxDb**?

 _std::cout << "************* SINR changing to " << snrInit << " (MCS = " << mcs << " ) *************" << std::endl;_ 
  
 _Simulator::Schedule (MicroSeconds(3*100), &MmWaveSpectrumPhy::UpdateSinrPerceived, 
 	enbDev->GetPhy()->GetDlSpectrumPhy (), specVals);_ 
  
 _//enbPhy->GenerateDataCqiReport(specVals);_ 
  
 _if (snrInit > snrMaxDb)_ 
  _{_ 
 _return;_ 
  _}_ 
  
  Thank you!

**Comment by zml312570140** [comment]
Hi DmitarC,

I guess it is a typo. This example was used for testing.
