### ISSUE TITLE
How to generate channel configuration?

### ISSUE THREAD

**Issue by PHAmorimRezende** [nyuwireless/ns3-mmwave#9]
Hello,

Reading page 04 of "A Framework for End-to-End Evaluation of 5G mmWave
Cellular Networks in ns-3" I can see that the channel matrices, optimal beamforming vectors and spatial signature matrices are generated using MATLAB. How can I generate these matrices and vectors? Do you have any script available?

Thank you,

**Comment by MengleiZhang** [comment]
Hi Pedro,

The MATLAB code is not available. However, you can take a look the new 3GPP channel implementation https://arxiv.org/abs/1702.04822 <https://arxiv.org/abs/1702.04822>, which generates the channel and beamforming vector directly in ns3. In mmwave-3gpp-channel.cc <http://mmwave-3gpp-channel.cc/> file,  channel matrix H_u_s_n is generated in function GetNewChannel, and the beamforming vector is calculated in function PowerMethodBeamforming.
